// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RecipeApplication.DataAccess.Models
{
    public partial class Recipe
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ImageUrl { get; set; }
        public string Comment { get; set; }
        public string Author { get; set; }
        public string Instruction { get; set; }
        public string Ingredients { get; set; }
    }
}